# Generated by Django 2.2.28 on 2025-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrandemonium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
