# Generated by Django 2.2.28 on 2025-03-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrandemonium', '0002_auto_20250326_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE')], max_length=10),
        ),
    ]
